export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const INVALIDATE_ELNEWS = 'INVALIDATE_ELNEWS';
export const REQUEST_NEXT_POSTS = 'REQUEST_NEXT_POSTS';
export const RECEIVE_NEXT_POSTS = 'RECEIVE_NEXT_POSTS';

export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const INVALIDATE_EVENTS = 'INVALIDATE_EVENTS';

export const REQUEST_LOGIN_URL = 'REQUEST_LOGIN_URL';
export const RECEIVE_LOGIN_URL = 'RECEIVE_LOGIN_URL';
export const SET_LOGGED = 'SET_LOGGED';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const SET_LOGOUT = 'SET_LOGOUT';

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_USER_INFO_BEGIN = 'GET_USER_INFO_BEGIN';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SET_CH_CONTENT = 'SET_CH_CONTENT';
export const SET_CH_INPUT = 'SET_CH_INPUT';
export const SET_CH_AUTHOR = 'SET_CH_AUTHOR';


export const REQUEST_CH_POST = 'REQUEST_CH_POST';
export const RECEIVE_CH_POST = 'RECEIVE_CH_POST';

export const ADMIN_LOGIN_BEGIN = 'ADMIN_LOGIN_BEGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';